import { addDays, subDays } from 'date-fns';
import { createPsaEvent } from './psa';
import type { ContainerCargoLine, Shipment } from './shipmentTypes';

function hoursAgo(h: number) {
  return Date.now() - h * 3600_000;
}

function dayIso(offset: number) {
  return addDays(new Date(), offset).toISOString();
}

const SUPPLIERS = [
  'Global Farms Suppliers',
  'Ocean Catch Suppliers',
  'Sunrise Dairy Co.',
  'Berry Farms Suppliers',
  'Valley Meats Inc.',
  'FreshPack Co.',
  'AgriGro Wholesale',
  'PureLand Creamery',
  'Plains Beef & Co.',
  'Valley Green Produce',
  'Midwest Dairy Group',
  'Coastal Citrus Co.',
];

const PRODUCTS: Array<{ product: string; unit: string; baseQty: number }> = [
  { product: 'Hard-Boiled Eggs', unit: 'Cases', baseQty: 800 },
  { product: 'Fresh Salmon', unit: 'Cases', baseQty: 200 },
  { product: 'Organic Milk', unit: 'Cases', baseQty: 400 },
  { product: 'Strawberries', unit: 'Cases', baseQty: 650 },
  { product: 'Chilled Beef', unit: 'Cases', baseQty: 320 },
  { product: 'Romaine Hearts', unit: 'Cases', baseQty: 900 },
  { product: 'Tuna Loins', unit: 'Cases', baseQty: 150 },
  { product: 'Hass Avocados', unit: 'Cases', baseQty: 500 },
  { product: 'Greek Yogurt', unit: 'Cases', baseQty: 280 },
  { product: 'Organic Cucumbers', unit: 'Cases', baseQty: 1100 },
  { product: 'Atlantic Cod', unit: 'Cases', baseQty: 180 },
  { product: 'Baby Spinach', unit: 'Cases', baseQty: 720 },
  { product: 'Chicken Breast', unit: 'Cases', baseQty: 450 },
  { product: 'Blueberries', unit: 'Cases', baseQty: 380 },
  { product: 'Butter Blocks', unit: 'Cases', baseQty: 260 },
  { product: 'Shrimp (IQF)', unit: 'Cases', baseQty: 220 },
];

const LAND_ROUTES = [
  { origin: 'Miami Reefer Yard', route: 'Miami → Chicago DC', originLat: 25.7781, originLng: -80.1797 },
  { origin: 'Wisconsin Creamery', route: 'Wisconsin → Chicago DC', originLat: 43.0731, originLng: -89.4012 },
  { origin: 'Salinas Grower Hub', route: 'Salinas → Chicago DC', originLat: 36.6777, originLng: -121.6555 },
  { origin: 'Kansas City Hub', route: 'KC → Chicago DC', originLat: 39.0997, originLng: -94.5786 },
  { origin: 'Yuma Greenhouse Yard', route: 'Yuma → Chicago DC', originLat: 32.6927, originLng: -114.6277 },
  { origin: 'Iowa Produce Cluster', route: 'Iowa → Chicago DC', originLat: 41.5868, originLng: -93.625 },
  { origin: 'Atlanta Cross-Dock', route: 'Atlanta → Chicago DC', originLat: 33.749, originLng: -84.388 },
  { origin: 'Dallas Cold Hub', route: 'Dallas → Chicago DC', originLat: 32.7767, originLng: -96.797 },
  { origin: 'Detroit Food Terminal', route: 'Detroit → Chicago DC', originLat: 42.3314, originLng: -83.0458 },
  { origin: 'Minneapolis Dairy Gate', route: 'Minneapolis → Chicago DC', originLat: 44.9778, originLng: -93.265 },
];

const SEA_ROUTES = [
  {
    origin: 'PSA Singapore — Tuas Port',
    route: 'Singapore → LA → Chicago DC',
    originLat: 1.2644,
    originLng: 103.666,
    terminal: 'PSA Tuas Terminal',
    vesselPrefix: 'MV Pacific',
  },
  {
    origin: 'PSA Busan Terminal',
    route: 'Busan → Seattle → Chicago DC',
    originLat: 35.1028,
    originLng: 129.0403,
    terminal: 'PSA Busan Gate',
    vesselPrefix: 'MV North Star',
  },
  {
    origin: 'Port of Rotterdam — Reefer Quay',
    route: 'Rotterdam → NY → Chicago DC',
    originLat: 51.9225,
    originLng: 4.4792,
    terminal: 'PSA / ECT Rotterdam',
    vesselPrefix: 'MV Atlantic Chill',
  },
  {
    origin: 'Port of Valparaíso',
    route: 'Valparaíso → LA → Chicago DC',
    originLat: -33.0472,
    originLng: -71.6127,
    terminal: 'PSA LatAm Partner Gate',
    vesselPrefix: 'MV Andes Fresh',
  },
  {
    origin: 'Port of Auckland',
    route: 'Auckland → Long Beach → Chicago DC',
    originLat: -36.8485,
    originLng: 174.7633,
    terminal: 'PSA Oceania Link',
    vesselPrefix: 'MV Kiwi Stream',
  },
  {
    origin: 'Port of Santos',
    route: 'Santos → Houston → Chicago DC',
    originLat: -23.9608,
    originLng: -46.3336,
    terminal: 'PSA Brasil Partner',
    vesselPrefix: 'MV Samba Cool',
  },
];

const STATUSES: Array<Shipment['status']> = ['on-time', 'on-time', 'on-time', 'delayed', 'delivered'];
const STAGES: Array<NonNullable<Shipment['stage']>> = ['delivering', 'delivering', 'delivering', 'packing', 'delivered'];
const BUYER_REFS = ['HQ DC Chicago', 'Lincoln Park', 'West Loop', 'River North', 'South Loop'];

/** Build multi-PO cargo for a shared container. */
function buildCargoLines(
  primaryId: string,
  primaryProduct: string,
  primaryQty: number,
  primaryUnit: string,
  seed: number,
  extraCount?: number
): ContainerCargoLine[] {
  const extras = extraCount ?? 2 + (seed % 5);
  const lines: ContainerCargoLine[] = [
    {
      poNumber: primaryId,
      product: primaryProduct,
      item: `${primaryQty.toLocaleString()} ${primaryUnit} of ${primaryProduct}`,
      quantity: primaryQty,
      unit: primaryUnit,
      sku: `SKU-${(1000 + seed).toString()}`,
      buyerRef: BUYER_REFS[seed % BUYER_REFS.length],
      lineStatus: 'shipped',
    },
  ];
  for (let j = 0; j < extras; j++) {
    const prod = PRODUCTS[(seed + j + 3) % PRODUCTS.length];
    const qty = prod.baseQty + ((seed + j) % 5) * 20;
    const poNum = `PO-2026-${(3000 + seed * 10 + j).toString()}`;
    lines.push({
      poNumber: poNum,
      product: prod.product,
      item: `${qty.toLocaleString()} ${prod.unit} of ${prod.product}`,
      quantity: qty,
      unit: prod.unit,
      sku: `SKU-${(2000 + seed * 10 + j).toString()}`,
      buyerRef: BUYER_REFS[(seed + j + 1) % BUYER_REFS.length],
      lineStatus: j === extras - 1 && seed % 7 === 0 ? 'partial' : 'shipped',
    });
  }
  return lines;
}

/** Generate a large mixed Sea + Land shipment catalog for buyer calendar / tracking demos. */
export function seedDefaultShipments(): Shipment[] {
  const now = new Date().toISOString();
  const destLat = 41.8781;
  const destLng = -87.6298;
  const count = 100;
  const list: Shipment[] = [];

  list.push({
    id: 'PO-2026-9912A',
    vendor: 'Ocean Catch Suppliers',
    item: '200 Cases of Fresh Salmon',
    product: 'Fresh Salmon',
    quantity: 200,
    unit: 'Cases',
    fleetSpecification: 'Ocean Reefer',
    logisticsRouteAndProvider: 'PSA Portnet · Tuas Terminal',
    status: 'on-time',
    eta: '2 Days',
    origin: 'PSA Singapore — Tuas Port',
    destination: 'Chicago DC',
    temp: '3°C [Stable]',
    route: 'Singapore → LA → Chicago DC',
    date: subDays(new Date(), 1).toISOString(),
    etaDate: dayIso(2),
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 3°C (Currently: 3.0°C)',
    containerNumber: 'PSAU8823147',
    vesselName: 'MV Pacific Fresh',
    voyageNumber: 'PF-229W',
    bookingNumber: 'SG-PSA-9912A',
    psaTerminal: 'PSA Tuas Terminal',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'ocean',
    originLat: 1.2644,
    originLng: 103.666,
    destLat,
    destLng,
    currentLat: 28.5,
    currentLng: -145.2,
    cargoLines: [
      {
        poNumber: 'PO-2026-9912A',
        product: 'Fresh Salmon',
        item: '200 Cases of Fresh Salmon',
        quantity: 200,
        unit: 'Cases',
        sku: 'SKU-SAL-9912',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-9912B',
        product: 'Tuna Loins',
        item: '120 Cases of Tuna Loins',
        quantity: 120,
        unit: 'Cases',
        sku: 'SKU-TUN-9912',
        buyerRef: 'Lincoln Park',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-9912C',
        product: 'Shrimp (IQF)',
        item: '180 Cases of Shrimp (IQF)',
        quantity: 180,
        unit: 'Cases',
        sku: 'SKU-SHP-9912',
        buyerRef: 'West Loop',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8840',
        product: 'Atlantic Cod',
        item: '90 Cases of Atlantic Cod',
        quantity: 90,
        unit: 'Cases',
        sku: 'SKU-COD-8840',
        buyerRef: 'River North',
        lineStatus: 'partial',
      },
    ],
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'PSA Portnet', {
        id: 'e-9912-1',
        timestamp: new Date(hoursAgo(120)).toISOString(),
        lat: 1.2644,
        lng: 103.666,
      }),
      createPsaEvent('GATE_IN', 'PSA Tuas Gate A', {
        id: 'e-9912-2',
        timestamp: new Date(hoursAgo(96)).toISOString(),
        lat: 1.2644,
        lng: 103.666,
      }),
      createPsaEvent('LOADED', 'MV Pacific Fresh · Bay 42', {
        id: 'e-9912-3',
        timestamp: new Date(hoursAgo(84)).toISOString(),
        lat: 1.2644,
        lng: 103.666,
        details: '4 purchase orders consolidated in PSAU8823147',
      }),
      createPsaEvent('VESSEL_DEPARTURE', 'Singapore Strait', {
        id: 'e-9912-4',
        timestamp: new Date(hoursAgo(72)).toISOString(),
        lat: 1.13,
        lng: 103.55,
      }),
      createPsaEvent('IN_TRANSIT_SEA', 'North Pacific', {
        id: 'e-9912-5',
        timestamp: new Date(hoursAgo(8)).toISOString(),
        lat: 28.5,
        lng: -145.2,
        details: 'AIS position synced via PSA Portnet',
      }),
    ],
  });

  // Showcase: active delayed stretch (red) + expected delay ahead (orange)
  list.push({
    id: 'PO-2026-DELAY1',
    vendor: 'Global Farms Suppliers',
    item: '1,200 Cases of Hard-Boiled Eggs',
    product: 'Hard-Boiled Eggs',
    quantity: 1200,
    unit: 'Cases',
    fleetSpecification: 'Active Refrigerated',
    logisticsRouteAndProvider: 'Route #402 Corridor · PSA Haulage',
    status: 'delayed',
    eta: '14 hrs (revised)',
    origin: 'Global Farms Plant #4 — Miami Port',
    destination: 'Chicago DC',
    temp: '5.8°C [Rising]',
    route: 'Miami → Chicago DC',
    date: subDays(new Date(), 1).toISOString(),
    etaDate: dayIso(1),
    hasAnomaly: true,
    expectedDelay: true,
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 3°C (Currently: 5.8°C)',
    shelfLifeDays: 14,
    shelfLifeDaysAtRisk: 9,
    storeOnHandCases: 180,
    dailyDemandCases: 120,
    containerNumber: 'FGUU4582190',
    vesselName: 'Road Reefer RT-402',
    voyageNumber: 'N/A',
    bookingNumber: 'BK-DELAY-402',
    psaTerminal: 'PSA Connected Haulage',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'road',
    originLat: 25.7781,
    originLng: -80.1797,
    destLat,
    destLng,
    // Mid-corridor — creates a visible red delayed stretch behind the asset
    currentLat: 35.2,
    currentLng: -86.8,
    cargoLines: buildCargoLines('PO-2026-DELAY1', 'Hard-Boiled Eggs', 1200, 'Cases', 42, 2),
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'Miami Reefer Yard', {
        id: 'e-delay-1',
        timestamp: new Date(hoursAgo(40)).toISOString(),
        lat: 25.7781,
        lng: -80.1797,
      }),
      createPsaEvent('GATE_OUT', 'Miami Gate B', {
        id: 'e-delay-2',
        timestamp: new Date(hoursAgo(36)).toISOString(),
        lat: 25.9,
        lng: -80.3,
      }),
      createPsaEvent('INLAND_TRANSIT', 'I-75 North', {
        id: 'e-delay-3',
        timestamp: new Date(hoursAgo(28)).toISOString(),
        lat: 30.1,
        lng: -83.2,
      }),
      createPsaEvent('TEMP_ALERT', 'Sector 4 Gateway — flash flood zone', {
        id: 'e-delay-4',
        timestamp: new Date(hoursAgo(10)).toISOString(),
        lat: 33.8,
        lng: -85.4,
        details: 'Delayed stretch: corridor congestion + reefer temp climb. ETA +14 hrs.',
      }),
      createPsaEvent('ETA_REVISED', 'Nashville bypass hold', {
        id: 'e-delay-5',
        timestamp: new Date(hoursAgo(4)).toISOString(),
        lat: 35.2,
        lng: -86.8,
        details: 'Expected delay ahead through Indianapolis corridor — PSA Portnet revised ETA.',
      }),
    ],
  });

  // Showcase: transport mode mismatch (expected ocean, but PSA events show inland)
  list.push({
    id: 'PO-2026-MISMATCH-OCEAN-AS-LAND',
    vendor: 'Global Farms Suppliers',
    item: '300 Cases of Mixed Leafy Greens',
    product: 'Mixed Leafy Greens',
    quantity: 300,
    unit: 'Cases',
    fleetSpecification: 'Reefer (Mismatch Demo)',
    logisticsRouteAndProvider: 'PSA Portnet · (expected) Ocean corridor',
    status: 'on-time',
    eta: '6 Days',
    origin: 'Miami DC Yard',
    destination: 'Chicago DC',
    temp: '4°C [Stable]',
    route: 'Miami → Chicago DC',
    date: subDays(new Date(), 1).toISOString(),
    etaDate: dayIso(6),
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 4°C (Currently: 4.0°C)',
    shelfLifeDays: 12,
    shelfLifeDaysAtRisk: 8,
    storeOnHandCases: 90,
    dailyDemandCases: 80,
    containerNumber: 'PSAU9911220',
    vesselName: 'MV Expected-Ocean (Mismatch)',
    voyageNumber: '—',
    bookingNumber: 'BK-MISMATCH-SEA-1',
    psaTerminal: 'PSA Connected Haulage',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'ocean',
    shippingMethod: 'Ocean freight',
    incoterms: 'CIF Miami',
    originLat: 25.7781,
    originLng: -80.1797,
    destLat,
    destLng,
    currentLat: 34.05,
    currentLng: -118.25,
    cargoLines: buildCargoLines('PO-2026-MISMATCH-OCEAN-AS-LAND', 'Mixed Leafy Greens', 300, 'Cases', 28, 3),
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'Miami Reefer Yard', {
        id: 'e-mis-1',
        timestamp: new Date(hoursAgo(50)).toISOString(),
        lat: 25.7781,
        lng: -80.1797,
      }),
      createPsaEvent('GATE_IN', 'Miami Gate A', {
        id: 'e-mis-2',
        timestamp: new Date(hoursAgo(44)).toISOString(),
        lat: 25.79,
        lng: -80.22,
      }),
      createPsaEvent('GATE_OUT', 'Miami Yard Exit', {
        id: 'e-mis-3',
        timestamp: new Date(hoursAgo(38)).toISOString(),
        lat: 26.2,
        lng: -80.35,
      }),
      createPsaEvent('INLAND_TRANSIT', 'I-75 North', {
        id: 'e-mis-4',
        timestamp: new Date(hoursAgo(24)).toISOString(),
        lat: 30.1,
        lng: -83.2,
      }),
      createPsaEvent('DC_ARRIVAL', 'Chicago DC Dock', {
        id: 'e-mis-5',
        timestamp: new Date(hoursAgo(10)).toISOString(),
        lat: destLat,
        lng: destLng,
      }),
    ],
  });

  // Showcase: air freight lots (for Global Fleet → Air view)
  list.push({
    id: 'PO-2026-AIR1',
    vendor: 'Ocean Catch Suppliers',
    item: '80 Cases of Fresh Tuna (Air)',
    product: 'Fresh Tuna',
    quantity: 80,
    unit: 'Cases',
    fleetSpecification: 'Air Cargo Cool Chain',
    logisticsRouteAndProvider: 'Air freight · ORD cool lane',
    status: 'on-time',
    eta: '18 hrs',
    origin: 'Tokyo Narita (NRT)',
    destination: 'Chicago DC',
    temp: '2°C [Stable]',
    route: 'Tokyo → Chicago (air)',
    date: subDays(new Date(), 0).toISOString(),
    etaDate: dayIso(1),
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 2°C (Currently: 2.0°C)',
    shelfLifeDays: 8,
    shelfLifeDaysAtRisk: 6,
    storeOnHandCases: 40,
    dailyDemandCases: 25,
    containerNumber: 'AIRU1002001',
    vesselName: 'Flight NH012 · Cool pallet',
    voyageNumber: 'NH012',
    bookingNumber: 'BK-AIR-NRT-1',
    psaTerminal: 'ORD Cold Cargo',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'air',
    shippingMethod: 'Air freight',
    originLat: 35.772,
    originLng: 140.3929,
    destLat,
    destLng,
    currentLat: 50.2,
    currentLng: -140.5,
    cargoLines: buildCargoLines('PO-2026-AIR1', 'Fresh Tuna', 80, 'Cases', 91, 1),
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'NRT Cool Cargo', {
        id: 'e-air1-1',
        timestamp: new Date(hoursAgo(20)).toISOString(),
        lat: 35.772,
        lng: 140.3929,
        details: 'Air freighter booking confirmed',
      }),
      createPsaEvent('GATE_OUT', 'NRT Gate C', {
        id: 'e-air1-2',
        timestamp: new Date(hoursAgo(14)).toISOString(),
        lat: 35.78,
        lng: 140.4,
        details: 'Pallet gated to aircraft',
      }),
      createPsaEvent('INLAND_TRANSIT', 'Pacific flight corridor', {
        id: 'e-air1-3',
        timestamp: new Date(hoursAgo(4)).toISOString(),
        lat: 50.2,
        lng: -140.5,
        details: 'Air position update · cool pallet stable',
      }),
    ],
  });

  list.push({
    id: 'PO-2026-AIR2',
    vendor: 'Global Farms Suppliers',
    item: '60 Cases of Berry Mix (Air)',
    product: 'Berry Mix',
    quantity: 60,
    unit: 'Cases',
    fleetSpecification: 'Air Cargo Cool Chain',
    logisticsRouteAndProvider: 'Air freight · AMS → ORD',
    status: 'delayed',
    eta: '22 hrs (revised)',
    origin: 'Amsterdam Schiphol (AMS)',
    destination: 'Chicago DC',
    temp: '3.4°C [Watch]',
    route: 'Amsterdam → Chicago (air)',
    date: subDays(new Date(), 0).toISOString(),
    etaDate: dayIso(1),
    hasAnomaly: true,
    expectedDelay: true,
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 3°C (Currently: 3.4°C)',
    shelfLifeDays: 7,
    shelfLifeDaysAtRisk: 4,
    storeOnHandCases: 20,
    dailyDemandCases: 18,
    containerNumber: 'AIRU1002002',
    vesselName: 'Flight KL611 · Cool pallet',
    voyageNumber: 'KL611',
    bookingNumber: 'BK-AIR-AMS-2',
    psaTerminal: 'ORD Cold Cargo',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'air',
    shippingMethod: 'Air freight',
    originLat: 52.3105,
    originLng: 4.7683,
    destLat,
    destLng,
    currentLat: 55.5,
    currentLng: -40.2,
    cargoLines: buildCargoLines('PO-2026-AIR2', 'Berry Mix', 60, 'Cases', 92, 1),
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'AMS Cool Hub', {
        id: 'e-air2-1',
        timestamp: new Date(hoursAgo(18)).toISOString(),
        lat: 52.3105,
        lng: 4.7683,
      }),
      createPsaEvent('ETA_REVISED', 'North Atlantic hold', {
        id: 'e-air2-2',
        timestamp: new Date(hoursAgo(3)).toISOString(),
        lat: 55.5,
        lng: -40.2,
        details: 'Air corridor delay · ETA +4 hrs',
      }),
    ],
  });

  // Showcase: on-time so far, but expected delay ahead (orange remaining path)
  list.push({
    id: 'PO-2026-EXPECT1',
    vendor: 'Ocean Catch Suppliers',
    item: '180 Cases of Fresh Salmon',
    product: 'Fresh Salmon',
    quantity: 180,
    unit: 'Cases',
    fleetSpecification: 'Ocean Reefer',
    logisticsRouteAndProvider: 'PSA Portnet · Tuas Terminal',
    status: 'on-time',
    eta: '3 Days (at risk)',
    origin: 'PSA Singapore — Tuas Port',
    destination: 'Chicago DC',
    temp: '3.1°C [Stable]',
    route: 'Singapore → LA → Chicago DC',
    date: subDays(new Date(), 2).toISOString(),
    etaDate: dayIso(3),
    hasAnomaly: false,
    expectedDelay: true,
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 3°C (Currently: 3.1°C)',
    shelfLifeDays: 12,
    shelfLifeDaysAtRisk: 8,
    storeOnHandCases: 40,
    dailyDemandCases: 55,
    containerNumber: 'PSAU7700144',
    vesselName: 'MV Pacific Fresh',
    voyageNumber: 'PF-231W',
    bookingNumber: 'SG-PSA-EXPECT1',
    psaTerminal: 'PSA Tuas Terminal',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'ocean',
    originLat: 1.2644,
    originLng: 103.666,
    destLat,
    destLng,
    currentLat: 20.5,
    currentLng: -155.0,
    cargoLines: buildCargoLines('PO-2026-EXPECT1', 'Fresh Salmon', 180, 'Cases', 77, 1),
    psaEvents: [
      createPsaEvent('VESSEL_DEPARTURE', 'Singapore Strait', {
        id: 'e-exp-1',
        timestamp: new Date(hoursAgo(72)).toISOString(),
        lat: 1.13,
        lng: 103.55,
      }),
      createPsaEvent('IN_TRANSIT_SEA', 'Central Pacific', {
        id: 'e-exp-2',
        timestamp: new Date(hoursAgo(24)).toISOString(),
        lat: 20.5,
        lng: -155.0,
      }),
      createPsaEvent('ETA_REVISED', 'LA berth congestion forecast', {
        id: 'e-exp-3',
        timestamp: new Date(hoursAgo(6)).toISOString(),
        lat: 25.0,
        lng: -140.0,
        details: 'Expected delay ahead: LA terminal berth wait ~18 hrs. Shelf life may compress on inland leg.',
      }),
    ],
  });

  // Ocean delay: natural weather / climate disruption on Pacific corridor
  list.push({
    id: 'PO-2026-OCEAN-WX1',
    vendor: 'Ocean Catch Suppliers',
    item: '420 Cases of Frozen Yellowfin Tuna',
    product: 'Frozen Yellowfin Tuna',
    quantity: 420,
    unit: 'Cases',
    fleetSpecification: '40ft High-Cube Reefer · Active Monitoring',
    logisticsRouteAndProvider: 'PSA Ocean · Singapore → Los Angeles → Chicago',
    status: 'delayed',
    eta: '6 Days (revised +36 hrs)',
    origin: 'PSA Singapore — Tuas Port',
    destination: 'Chicago DC',
    temp: '-18.2°C [Stable]',
    route: 'Singapore → Pacific Ocean → Los Angeles → Chicago DC',
    date: subDays(new Date(), 7).toISOString(),
    etaDate: dayIso(6),
    hasAnomaly: true,
    expectedDelay: true,
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Frozen Target: -18°C (Currently: -18.2°C)',
    shelfLifeDays: 120,
    shelfLifeDaysAtRisk: 112,
    storeOnHandCases: 190,
    dailyDemandCases: 45,
    containerNumber: 'PSAU6602841',
    vesselName: 'MV Meridian Star',
    voyageNumber: 'MS-408E',
    bookingNumber: 'SG-PSA-WX-408',
    psaTerminal: 'PSA Tuas Terminal',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'ocean',
    shippingMethod: 'Ocean freight',
    incoterms: 'CIF Los Angeles',
    portOfLoading: 'Singapore — Tuas',
    portOfDischarge: 'Los Angeles — Pier 400',
    originLat: 1.2644,
    originLng: 103.666,
    destLat,
    destLng,
    currentLat: 18.9,
    currentLng: 137.4,
    cargoLines: buildCargoLines(
      'PO-2026-OCEAN-WX1',
      'Frozen Yellowfin Tuna',
      420,
      'Cases',
      118,
      2
    ),
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'PSA Tuas Terminal', {
        id: 'e-ocean-wx-1',
        timestamp: new Date(hoursAgo(180)).toISOString(),
        lat: 1.2644,
        lng: 103.666,
        details: 'Reefer booking and power-point allocation confirmed',
      }),
      createPsaEvent('VESSEL_DEPARTURE', 'Singapore Strait', {
        id: 'e-ocean-wx-2',
        timestamp: new Date(hoursAgo(156)).toISOString(),
        lat: 1.13,
        lng: 103.55,
        details: 'Departed on scheduled Pacific service',
      }),
      createPsaEvent('IN_TRANSIT_SEA', 'Philippine Sea', {
        id: 'e-ocean-wx-3',
        timestamp: new Date(hoursAgo(76)).toISOString(),
        lat: 14.8,
        lng: 132.1,
        details: 'AIS position received · reefer telemetry stable',
      }),
      createPsaEvent('WEATHER_ALERT', 'Western Pacific — typhoon avoidance zone', {
        id: 'e-ocean-wx-4',
        timestamp: new Date(hoursAgo(18)).toISOString(),
        lat: 18.2,
        lng: 136.0,
        details:
          'Severe tropical cyclone and 7–9 m swells forced a northern deviation. Vessel speed reduced; climate disruption adds ~36 hrs.',
      }),
      createPsaEvent('ETA_REVISED', 'Pacific weather-routing corridor', {
        id: 'e-ocean-wx-5',
        timestamp: new Date(hoursAgo(6)).toISOString(),
        lat: 18.9,
        lng: 137.4,
        details:
          'PSA revised Los Angeles berth ETA by +36 hrs. Cold-chain remains stable; inland appointment requires rescheduling.',
      }),
    ],
  });

  // Ocean delay: destination port / terminal congestion
  list.push({
    id: 'PO-2026-OCEAN-PORT1',
    vendor: 'FreshPack Co.',
    item: '760 Cases of European Dairy & Cheese',
    product: 'European Dairy & Cheese',
    quantity: 760,
    unit: 'Cases',
    fleetSpecification: '40ft Reefer · Controlled Atmosphere',
    logisticsRouteAndProvider: 'Maersk / Portnet · Rotterdam → Newark → Chicago',
    status: 'delayed',
    eta: '4 Days (revised +28 hrs)',
    origin: 'Port of Rotterdam — Maasvlakte II',
    destination: 'Chicago DC',
    temp: '2.6°C [Stable]',
    route: 'Rotterdam → North Atlantic → Newark → Chicago DC',
    date: subDays(new Date(), 9).toISOString(),
    etaDate: dayIso(4),
    hasAnomaly: true,
    expectedDelay: true,
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Chilled Target: 2–4°C (Currently: 2.6°C)',
    shelfLifeDays: 28,
    shelfLifeDaysAtRisk: 22,
    storeOnHandCases: 240,
    dailyDemandCases: 85,
    containerNumber: 'MSCU7419032',
    vesselName: 'MV Atlantic Horizon',
    voyageNumber: 'AH-117W',
    bookingNumber: 'RTM-EWR-117',
    psaTerminal: 'Port Newark Container Terminal',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'ocean',
    shippingMethod: 'Ocean freight',
    incoterms: 'CIF Newark',
    portOfLoading: 'Rotterdam — Maasvlakte II',
    portOfDischarge: 'Newark — PNCT',
    originLat: 51.95,
    originLng: 4.05,
    destLat,
    destLng,
    currentLat: 40.2,
    currentLng: -66.3,
    cargoLines: buildCargoLines(
      'PO-2026-OCEAN-PORT1',
      'European Dairy & Cheese',
      760,
      'Cases',
      119,
      3
    ),
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'Rotterdam Maasvlakte II', {
        id: 'e-ocean-port-1',
        timestamp: new Date(hoursAgo(216)).toISOString(),
        lat: 51.95,
        lng: 4.05,
        details: 'Reefer booking and terminal slot confirmed',
      }),
      createPsaEvent('LOADED', 'MV Atlantic Horizon · Rotterdam', {
        id: 'e-ocean-port-2',
        timestamp: new Date(hoursAgo(194)).toISOString(),
        lat: 51.95,
        lng: 4.05,
        details: 'Three purchase orders consolidated and loaded',
      }),
      createPsaEvent('VESSEL_DEPARTURE', 'English Channel', {
        id: 'e-ocean-port-3',
        timestamp: new Date(hoursAgo(180)).toISOString(),
        lat: 50.4,
        lng: -1.8,
      }),
      createPsaEvent('IN_TRANSIT_SEA', 'North Atlantic', {
        id: 'e-ocean-port-4',
        timestamp: new Date(hoursAgo(42)).toISOString(),
        lat: 40.2,
        lng: -66.3,
        details: 'Approaching New York / New Jersey pilot station',
      }),
      createPsaEvent('PORT_CONGESTION', 'Port Newark Container Terminal', {
        id: 'e-ocean-port-5',
        timestamp: new Date(hoursAgo(12)).toISOString(),
        lat: 40.684,
        lng: -74.151,
        details:
          'Berth occupancy 96%; labor window and reefer plug availability constrained. Estimated anchorage / berth wait: 28 hrs.',
      }),
      createPsaEvent('ETA_REVISED', 'New York / New Jersey anchorage', {
        id: 'e-ocean-port-6',
        timestamp: new Date(hoursAgo(3)).toISOString(),
        lat: 40.55,
        lng: -73.95,
        details:
          'Terminal discharge and gate-out appointments moved by +28 hrs. DP bill and warehouse receiving slot should be re-planned.',
      }),
    ],
  });

  // Showcase: multi-PO protein consolidation (6 PO lines in one reefer)
  list.push({
    id: 'PO-2026-CONSOL-SEA1',
    vendor: 'Ocean Catch Suppliers',
    item: 'Mixed seafood program (6 POs)',
    product: 'Fresh Salmon',
    quantity: 980,
    unit: 'Cases',
    fleetSpecification: '40ft High-Cube Reefer · Multi-PO',
    logisticsRouteAndProvider: 'PSA Ocean · Busan → Seattle → Chicago',
    status: 'on-time',
    eta: '5 Days',
    origin: 'PSA Busan Terminal',
    destination: 'Chicago DC',
    temp: '2°C [Stable]',
    route: 'Busan → Seattle → Chicago DC',
    date: subDays(new Date(), 4).toISOString(),
    etaDate: dayIso(5),
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 2°C (Currently: 2.0°C)',
    containerNumber: 'MSKU7788991',
    vesselName: 'MV North Star 88',
    voyageNumber: 'NS-312E',
    bookingNumber: 'BK-MSKU-7788',
    asnNumber: 'ASN-2026-SEA-7788',
    psaTerminal: 'PSA Busan Gate',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'ocean',
    originLat: 35.1028,
    originLng: 129.0403,
    destLat,
    destLng,
    currentLat: 48.5,
    currentLng: -130.2,
    cargoLines: [
      {
        poNumber: 'PO-2026-CONSOL-SEA1',
        product: 'Fresh Salmon',
        item: '220 Cases Fresh Salmon',
        quantity: 220,
        unit: 'Cases',
        sku: 'SKU-SAL-7788-A',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8841',
        product: 'Tuna Loins',
        item: '180 Cases Tuna Loins',
        quantity: 180,
        unit: 'Cases',
        sku: 'SKU-TUN-8841',
        buyerRef: 'Lincoln Park',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8842',
        product: 'Atlantic Cod',
        item: '140 Cases Atlantic Cod',
        quantity: 140,
        unit: 'Cases',
        sku: 'SKU-COD-8842',
        buyerRef: 'West Loop',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8843',
        product: 'Shrimp (IQF)',
        item: '160 Cases Shrimp (IQF)',
        quantity: 160,
        unit: 'Cases',
        sku: 'SKU-SHP-8843',
        buyerRef: 'River North',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8844',
        product: 'Fresh Salmon',
        item: '150 Cases Fresh Salmon — fillet',
        quantity: 150,
        unit: 'Cases',
        sku: 'SKU-SAL-8844',
        buyerRef: 'South Loop',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8845',
        product: 'Tuna Loins',
        item: '130 Cases Tuna Loins — sushi grade',
        quantity: 130,
        unit: 'Cases',
        sku: 'SKU-TUN-8845',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'partial',
      },
    ],
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'PSA Busan Gate', {
        id: 'e-consol-sea-1',
        timestamp: new Date(hoursAgo(120)).toISOString(),
        lat: 35.1028,
        lng: 129.0403,
        details: 'Six purchase orders consolidated into MSKU7788991',
      }),
      createPsaEvent('LOADED', 'MV North Star 88 · Busan', {
        id: 'e-consol-sea-2',
        timestamp: new Date(hoursAgo(96)).toISOString(),
        lat: 35.1028,
        lng: 129.0403,
      }),
      createPsaEvent('IN_TRANSIT_SEA', 'North Pacific', {
        id: 'e-consol-sea-3',
        timestamp: new Date(hoursAgo(12)).toISOString(),
        lat: 48.5,
        lng: -130.2,
      }),
    ],
  });

  // Showcase: dairy + eggs road consolidation (5 PO lines)
  list.push({
    id: 'PO-2026-CONSOL-ROAD1',
    vendor: 'Sunrise Dairy Co.',
    item: 'Dairy & protein mixed load (5 POs)',
    product: 'Organic Milk',
    quantity: 1420,
    unit: 'Cases',
    fleetSpecification: 'Road Reefer 53ft · Multi-PO',
    logisticsRouteAndProvider: 'Midwest Reefer · Wisconsin → Chicago',
    status: 'on-time',
    eta: '1 Day',
    origin: 'Wisconsin Creamery',
    destination: 'Chicago DC',
    temp: '3°C [Stable]',
    route: 'Wisconsin → Chicago DC',
    date: subDays(new Date(), 1).toISOString(),
    etaDate: dayIso(1),
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 3°C (Currently: 3.1°C)',
    containerNumber: 'CXDU3344556',
    vesselName: 'Road Reefer RT-518',
    voyageNumber: 'N/A',
    bookingNumber: 'BK-CXDU-3344',
    asnNumber: 'ASN-2026-DAIRY-3344',
    psaTerminal: 'PSA Connected Haulage',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'road',
    originLat: 43.0731,
    originLng: -89.4012,
    destLat,
    destLng,
    currentLat: 42.1,
    currentLng: -88.4,
    cargoLines: [
      {
        poNumber: 'PO-2026-CONSOL-ROAD1',
        product: 'Organic Milk',
        item: '400 Cases Organic Milk',
        quantity: 400,
        unit: 'Cases',
        sku: 'SKU-MILK-3344',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8850',
        product: 'Greek Yogurt',
        item: '320 Cases Greek Yogurt',
        quantity: 320,
        unit: 'Cases',
        sku: 'SKU-YOG-8850',
        buyerRef: 'Lincoln Park',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8851',
        product: 'Butter Blocks',
        item: '280 Cases Butter Blocks',
        quantity: 280,
        unit: 'Cases',
        sku: 'SKU-BTR-8851',
        buyerRef: 'West Loop',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8852',
        product: 'Hard-Boiled Eggs',
        item: '260 Cases Hard-Boiled Eggs',
        quantity: 260,
        unit: 'Cases',
        sku: 'SKU-EGG-8852',
        buyerRef: 'River North',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-2026-8853',
        product: 'Organic Milk',
        item: '160 Cases Organic Milk — lactose free',
        quantity: 160,
        unit: 'Cases',
        sku: 'SKU-MILK-8853',
        buyerRef: 'South Loop',
        lineStatus: 'shipped',
      },
    ],
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'Wisconsin Creamery', {
        id: 'e-consol-road-1',
        timestamp: new Date(hoursAgo(36)).toISOString(),
        lat: 43.0731,
        lng: -89.4012,
        details: 'Five PO lines loaded into CXDU3344556',
      }),
      createPsaEvent('INLAND_TRANSIT', 'I-94 East', {
        id: 'e-consol-road-2',
        timestamp: new Date(hoursAgo(8)).toISOString(),
        lat: 42.1,
        lng: -88.4,
      }),
    ],
  });

  // Showcase: berry multi-PO ocean container (links to Purchase Orders demo)
  list.push({
    id: 'PO-2026-BERRY-CONSOL',
    vendor: 'Berry Farms Co-op',
    item: 'Berry program — 7 PO lines consolidated',
    product: 'Blueberries',
    quantity: 6450,
    unit: 'Cases',
    fleetSpecification: '40ft Reefer · Berry consolidation',
    logisticsRouteAndProvider: 'Hapag-Lloyd · Valparaíso → LA → Chicago',
    status: 'delayed',
    eta: '3 Days (+1 day delay)',
    origin: 'Valparaíso, Chile',
    destination: 'Chicago DC',
    temp: '1°C [Stable]',
    route: 'Valparaíso → LA → Chicago DC',
    date: subDays(new Date(), 5).toISOString(),
    etaDate: dayIso(3),
    expectedDelay: true,
    stage: 'delivering',
    packingProgress: 100,
    preCoolingTarget: 'Pre-Cooling Target: 1°C (Currently: 1.1°C)',
    containerNumber: 'HLXU5520198',
    vesselName: 'MV Cordillera Express',
    voyageNumber: 'CE-204W',
    bookingNumber: 'HLXU-5520198',
    asnNumber: 'ASN-2026-BB-0810',
    psaTerminal: 'PSA LatAm Partner Gate',
    psaSyncStatus: 'synced',
    psaLastSyncAt: now,
    transportMode: 'ocean',
    originLat: -33.0472,
    originLng: -71.6127,
    destLat,
    destLng,
    currentLat: 32.8,
    currentLng: -118.4,
    cargoLines: [
      {
        poNumber: 'PO-4500012401',
        product: 'Blueberries',
        item: '1,200 Cases Blueberries — Premium',
        quantity: 1200,
        unit: 'Cases',
        sku: 'SKU-BB-2401-A',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-4500012401',
        product: 'Blueberries',
        item: '900 Cases Blueberries — Grade B',
        quantity: 900,
        unit: 'Cases',
        sku: 'SKU-BB-2401-B',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-4500012401',
        product: 'Blueberries',
        item: '600 Cases Blueberries — Organic',
        quantity: 600,
        unit: 'Cases',
        sku: 'SKU-BB-2401-O',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-4500012401',
        product: 'Blueberries',
        item: '900 Cases Blueberries — Family Pack',
        quantity: 900,
        unit: 'Cases',
        sku: 'SKU-BB-2401-F',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-4500012402',
        product: 'Strawberries',
        item: '1,100 Cases Strawberries — Driscoll',
        quantity: 1100,
        unit: 'Cases',
        sku: 'SKU-ST-2402-A',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-4500012402',
        product: 'Strawberries',
        item: '950 Cases Strawberries — Standard',
        quantity: 950,
        unit: 'Cases',
        sku: 'SKU-ST-2402-B',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
      {
        poNumber: 'PO-4500012402',
        product: 'Strawberries',
        item: '800 Cases Strawberries — Pint',
        quantity: 800,
        unit: 'Cases',
        sku: 'SKU-ST-2402-P',
        buyerRef: 'HQ DC Chicago',
        lineStatus: 'shipped',
      },
    ],
    psaEvents: [
      createPsaEvent('BOOKING_CONFIRMED', 'Valparaíso Export', {
        id: 'e-berry-consol-1',
        timestamp: subDays(new Date(), 8).toISOString(),
        lat: -33.0472,
        lng: -71.6127,
        details: 'PO-4500012401 (4 lines) + PO-4500012402 (3 lines) consolidated',
      }),
      createPsaEvent('GATE_IN', 'PSA LatAm Partner Gate', {
        id: 'e-berry-consol-2',
        timestamp: subDays(new Date(), 6).toISOString(),
        lat: -33.0472,
        lng: -71.6127,
      }),
      createPsaEvent('IN_TRANSIT_SEA', 'Pacific corridor', {
        id: 'e-berry-consol-3',
        timestamp: subDays(new Date(), 1).toISOString(),
        lat: 32.8,
        lng: -118.4,
      }),
      createPsaEvent('ETA_REVISED', 'LA berth wait', {
        id: 'e-berry-consol-4',
        timestamp: new Date(hoursAgo(6)).toISOString(),
        lat: 33.7,
        lng: -118.2,
        details: 'Consolidated berry load ETA +24 hrs',
      }),
    ],
  });

  // Supplier packing queue — pending delivery confirmation / shipment details
  list.push({
    id: 'PO-2026-PEND1',
    vendor: 'Global Farms Suppliers',
    item: '800 Cases of Hass Avocados',
    product: 'Hass Avocados',
    quantity: 800,
    unit: 'Cases',
    fleetSpecification: 'Active Refrigerated',
    logisticsRouteAndProvider: 'Corridor 418 · PSA Haulage',
    status: 'on-time',
    eta: 'Pending dispatch',
    origin: 'Global Farms Packhouse — Salinas',
    destination: 'Chicago DC',
    temp: '4.0°C',
    route: 'Salinas → Chicago DC',
    date: now,
    etaDate: dayIso(4),
    stage: 'packing',
    packingProgress: 55,
    preCoolingTarget: 'Pre-Cooling Target: 4°C (Currently: 4.2°C)',
    containerNumber: 'FGRU8800121',
    vesselName: 'Road Reefer RT-418',
    voyageNumber: 'N/A',
    bookingNumber: 'BK-PEND-418',
    psaTerminal: 'PSA Connected Haulage',
    psaSyncStatus: 'pending',
    psaLastSyncAt: now,
    transportMode: 'road',
    originLat: 36.6777,
    originLng: -121.6555,
    destLat,
    destLng,
    currentLat: 36.6777,
    currentLng: -121.6555,
    cargoLines: buildCargoLines('PO-2026-PEND1', 'Hass Avocados', 800, 'Cases', 11, 1),
  });

  list.push({
    id: 'PO-2026-PEND2',
    vendor: 'Global Farms Suppliers',
    item: '1,100 Cases of Organic Cucumbers',
    product: 'Organic Cucumbers',
    quantity: 1100,
    unit: 'Cases',
    fleetSpecification: 'Active Refrigerated',
    logisticsRouteAndProvider: 'Corridor 422 · PSA Haulage',
    status: 'on-time',
    eta: 'Pending dispatch',
    origin: 'Global Farms Greenhouse — Yuma',
    destination: 'Chicago DC',
    temp: '3.5°C',
    route: 'Yuma → Chicago DC',
    date: now,
    etaDate: dayIso(3),
    stage: 'packing',
    packingProgress: 35,
    preCoolingTarget: 'Pre-Cooling Target: 3°C (Currently: 5.1°C)',
    containerNumber: 'FGRU8800199',
    vesselName: 'Road Reefer RT-422',
    voyageNumber: 'N/A',
    bookingNumber: 'BK-PEND-422',
    psaTerminal: 'PSA Connected Haulage',
    psaSyncStatus: 'pending',
    psaLastSyncAt: now,
    transportMode: 'road',
    originLat: 32.6927,
    originLng: -114.6277,
    destLat,
    destLng,
    currentLat: 32.6927,
    currentLng: -114.6277,
    cargoLines: buildCargoLines('PO-2026-PEND2', 'Organic Cucumbers', 1100, 'Cases', 22, 2),
  });

  for (let i = 1; i <= count; i++) {
    const id = `PO-2026-${(1000 + i).toString()}`;
    if (
      id === 'PO-2026-9912A' ||
      id === 'PO-2026-DELAY1' ||
      id === 'PO-2026-EXPECT1' ||
      id === 'PO-2026-PEND1' ||
      id === 'PO-2026-PEND2' ||
      id === 'PO-2026-CONSOL-SEA1' ||
      id === 'PO-2026-CONSOL-ROAD1' ||
      id === 'PO-2026-BERRY-CONSOL' ||
      list.some((s) => s.id === id)
    )
      continue;

    const isOcean = i % 5 === 0 || i % 5 === 1;
    const supplier = SUPPLIERS[i % SUPPLIERS.length];
    const prod = PRODUCTS[i % PRODUCTS.length];
    const status = STATUSES[i % STATUSES.length];
    let stage = STAGES[i % STAGES.length];
    if (status === 'delivered') stage = 'delivered';
    if (status === 'delayed' && stage === 'delivered') stage = 'delivering';

    const etaOffset = status === 'delivered' ? -((i % 10) + 1) : i % 28;
    const qty = prod.baseQty + (i % 7) * 25;
    const syncPending = i % 11 === 0;
    const cargoLines = buildCargoLines(id, prod.product, qty, prod.unit, i);

    if (isOcean) {
      const sea = SEA_ROUTES[i % SEA_ROUTES.length];
      const voyage = `${sea.vesselPrefix.split(' ').pop()?.slice(0, 2).toUpperCase() || 'VX'}-${200 + (i % 80)}${i % 2 === 0 ? 'W' : 'E'}`;
      list.push({
        id,
        vendor: supplier,
        item: `${qty.toLocaleString()} ${prod.unit} of ${prod.product}`,
        product: prod.product,
        quantity: qty,
        unit: prod.unit,
        fleetSpecification: 'Ocean Reefer',
        logisticsRouteAndProvider: `PSA Portnet · ${sea.terminal}`,
        status,
        eta: status === 'delivered' ? 'Closed' : `${Math.max(1, etaOffset || 1)} Days`,
        origin: sea.origin,
        destination: i % 4 === 0 ? 'Lincoln Park Store' : 'Chicago DC',
        temp: `${(i % 5) - 1}.${i % 9}°C`,
        route: sea.route,
        date: subDays(new Date(), (i % 6) + 1).toISOString(),
        etaDate: dayIso(etaOffset),
        hasAnomaly: status === 'delayed',
        stage,
        packingProgress: stage === 'packing' ? 40 + (i % 50) : 100,
        preCoolingTarget: `Pre-Cooling Target: 3°C (Currently: ${(i % 5) - 1}.${i % 9}°C)`,
        containerNumber: `PSAU${(8800000 + i * 137).toString().slice(0, 7)}`,
        vesselName: `${sea.vesselPrefix} ${100 + (i % 50)}`,
        voyageNumber: voyage,
        bookingNumber: `SG-PSA-${1000 + i}`,
        psaTerminal: sea.terminal,
        psaSyncStatus: syncPending ? 'pending' : 'synced',
        psaLastSyncAt: now,
        transportMode: 'ocean',
        originLat: sea.originLat,
        originLng: sea.originLng,
        destLat,
        destLng,
        currentLat: sea.originLat + ((i % 20) - 10) * 1.5,
        currentLng: sea.originLng + ((i % 30) - 15) * 2,
        cargoLines,
      });
    } else {
      const land = LAND_ROUTES[i % LAND_ROUTES.length];
      list.push({
        id,
        vendor: supplier,
        item: `${qty.toLocaleString()} ${prod.unit} of ${prod.product}`,
        product: prod.product,
        quantity: qty,
        unit: prod.unit,
        fleetSpecification: 'Active Refrigerated',
        logisticsRouteAndProvider: `Corridor ${400 + (i % 40)} · PSA Haulage`,
        status,
        eta:
          status === 'delivered'
            ? 'Closed'
            : etaOffset === 0
              ? `${8 + (i % 12)} hrs`
              : `${Math.max(1, etaOffset)} Days`,
        origin: land.origin,
        destination: i % 5 === 0 ? 'West Loop Store' : 'Chicago DC',
        temp: `${2 + (i % 4)}.${i % 9}°C`,
        route: land.route,
        date: subDays(new Date(), i % 5).toISOString(),
        etaDate: dayIso(etaOffset),
        hasAnomaly: status === 'delayed',
        stage,
        packingProgress: stage === 'packing' ? 35 + (i % 55) : 100,
        preCoolingTarget: `Pre-Cooling Target: 3°C (Currently: ${2 + (i % 4)}.${i % 9}°C)`,
        containerNumber: `FGRU${(2200000 + i * 211).toString().slice(0, 7)}`,
        vesselName: `Road Reefer RT-${400 + (i % 90)}`,
        voyageNumber: 'N/A',
        bookingNumber: `BK-${1000 + i}-LD`,
        psaTerminal: 'PSA Connected Haulage',
        psaSyncStatus: syncPending ? 'pending' : 'synced',
        psaLastSyncAt: now,
        transportMode: 'road',
        originLat: land.originLat,
        originLng: land.originLng,
        destLat,
        destLng,
        currentLat: land.originLat + (destLat - land.originLat) * ((i % 7) / 10 + 0.2),
        currentLng: land.originLng + (destLng - land.originLng) * ((i % 7) / 10 + 0.2),
        cargoLines,
      });
    }
  }

  return list.map((s) => enrichWithPsaDefaults(s));
}

export function enrichWithPsaDefaults(s: Shipment): Shipment {
  const withCargo: Shipment = {
    ...s,
    cargoLines:
      s.cargoLines?.length
        ? s.cargoLines
        : buildCargoLines(
            s.id,
            s.product || s.item,
            s.quantity || 100,
            s.unit || 'Cases',
            s.id.split('').reduce((a, c) => a + c.charCodeAt(0), 0) % 97,
            1 + (s.id.length % 3)
          ),
  };

  if (withCargo.containerNumber && withCargo.psaEvents?.length) {
    return {
      ...withCargo,
      psaSyncStatus: withCargo.psaSyncStatus || 'synced',
      psaLastSyncAt: withCargo.psaLastSyncAt || new Date().toISOString(),
      destLat: withCargo.destLat ?? 41.8781,
      destLng: withCargo.destLng ?? -87.6298,
      etaDate: withCargo.etaDate || withCargo.date,
    };
  }
  const hash = withCargo.id.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  const isOcean = withCargo.transportMode === 'ocean';
  return {
    ...withCargo,
    containerNumber:
      withCargo.containerNumber ||
      `${isOcean ? 'PSAU' : 'FGUU'}${(1000000 + (hash % 8999999)).toString().slice(0, 7)}`,
    vesselName:
      withCargo.vesselName ||
      (isOcean ? 'MV FreshGuard Link' : `Road Reefer RT-${hash % 900}`),
    voyageNumber: withCargo.voyageNumber || (isOcean ? `FG-${hash % 400}W` : 'N/A'),
    bookingNumber: withCargo.bookingNumber || `BK-${withCargo.id.slice(-4)}`,
    psaTerminal: withCargo.psaTerminal || (isOcean ? 'PSA Portnet Connected' : 'PSA Connected Haulage'),
    psaSyncStatus: withCargo.psaSyncStatus || 'synced',
    psaLastSyncAt: withCargo.psaLastSyncAt || new Date().toISOString(),
    transportMode: withCargo.transportMode || (isOcean ? 'ocean' : 'road'),
    originLat: withCargo.originLat ?? 25.7 + (hash % 20),
    originLng: withCargo.originLng ?? -90 + (hash % 30),
    destLat: withCargo.destLat ?? 41.8781,
    destLng: withCargo.destLng ?? -87.6298,
    currentLat: withCargo.currentLat ?? 35 + (hash % 10),
    currentLng: withCargo.currentLng ?? -88 + (hash % 8),
    etaDate: withCargo.etaDate || withCargo.date,
    psaEvents: withCargo.psaEvents?.length
      ? withCargo.psaEvents
      : isOcean
        ? [
            createPsaEvent('BOOKING_CONFIRMED', withCargo.origin || 'PSA Terminal', {
              timestamp: subDays(new Date(), 4).toISOString(),
            }),
            createPsaEvent('GATE_IN', withCargo.psaTerminal || 'PSA Gate', {
              timestamp: subDays(new Date(), 3).toISOString(),
            }),
            createPsaEvent('IN_TRANSIT_SEA', withCargo.route || 'Ocean corridor', {
              timestamp: new Date().toISOString(),
            }),
          ]
        : [
            createPsaEvent('BOOKING_CONFIRMED', withCargo.origin || 'Supplier', {
              timestamp: subDays(new Date(), 2).toISOString(),
            }),
            createPsaEvent('INLAND_TRANSIT', withCargo.route || 'Corridor', {
              timestamp: new Date().toISOString(),
            }),
          ],
  };
}
